name: gosi_hakathon_madmun_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  cached_network_image: ^3.3.1
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.10+1
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/image_not_found.png
    - assets/images/side-menu-icon.png
    - assets/images/img_growth_1.png
    - assets/images/user-icon.png
    - assets/images/document-text.png
    - assets/images/money-recive.png
    - assets/images/wallet-check.png
    - assets/images/home-icon.png
    - assets/images/logo-general-organization-for-social-insurance.png
    - assets/images/img_1.png
    - assets/images/img_financial_growth.png
    - assets/images/img_growth_2.png
    - assets/images/chatpot.png


  fonts:
    - family: ManropeBold
      fonts:
        - asset: assets/fonts/ManropeBold.ttf
    - family: TajawalBold
      fonts:
        - asset: assets/fonts/TajawalBold.ttf
