// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnqk7i4__ZphuNcCiqzyjfZ4CBFFuS3DQ',
    appId: '1:8882802715:web:f275d6d4a07d93866ae8be',
    messagingSenderId: '8882802715',
    projectId: 'madmun-2e5d9',
    authDomain: 'madmun-2e5d9.firebaseapp.com',
    storageBucket: 'madmun-2e5d9.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9MyobRI5nYrmTTRgxi1EAkTwaXBrleeE',
    appId: '1:8882802715:android:9dc044c7356284ea6ae8be',
    messagingSenderId: '8882802715',
    projectId: 'madmun-2e5d9',
    storageBucket: 'madmun-2e5d9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_KqaUq7fYGrRxiVC3hMw8uTgXxZ6oIGg',
    appId: '1:8882802715:ios:6f87c4f38d4be0576ae8be',
    messagingSenderId: '8882802715',
    projectId: 'madmun-2e5d9',
    storageBucket: 'madmun-2e5d9.appspot.com',
    iosBundleId: 'com.example.gosiHakathonMadmunApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_KqaUq7fYGrRxiVC3hMw8uTgXxZ6oIGg',
    appId: '1:8882802715:ios:7d888bff9f44a0e36ae8be',
    messagingSenderId: '8882802715',
    projectId: 'madmun-2e5d9',
    storageBucket: 'madmun-2e5d9.appspot.com',
    iosBundleId: 'com.example.gosiHakathonMadmunApp.RunnerTests',
  );
}
